Canvas Event Handlers Added
arshithsuresh/training-arshith pull request #2
Opened 2022-11-04 06:12 UTC by arshithsuresh

2022-11-04 09:26 UTC, isham-mohamed requested changes

2022-11-04 09:26 UTC, isham-mohamed commented on src/app/core/logging/eventInspectorLogger.ts
> +}
remove unused methods

2022-11-04 09:26 UTC, isham-mohamed commented on src/app/core/events/objectRotatedEvent.ts
> +    }
can be moved to abstract class

2022-11-04 09:26 UTC, isham-mohamed commented on src/app/core/events/objectMovedEvent.ts
> +
check with moved event

2022-11-04 09:26 UTC, isham-mohamed commented on src/app/core/logging/event-handle.service.ts
> +            })
move to canvas component

2022-11-06 17:32 UTC, arshithsuresh commented on src/app/core/logging/event-handle.service.ts
> +            })
Moved

2022-11-06 17:32 UTC, arshithsuresh commented on src/app/core/events/objectRotatedEvent.ts
> +    }
Done

2022-11-06 17:32 UTC, arshithsuresh commented on src/app/core/logging/eventInspectorLogger.ts
> +}
Removed

2022-11-07 06:55 UTC, isham-mohamed approved these changes

2022-11-07 07:01 UTC, merged